### PR TITLE
Changed developers info tile and added Add Friends API

### PR DESCRIPTION
**Pull request by Sandesh1013**

### CODE REVIEW

**Comment by Jashpatel1** [comment]
@Sandesh1013 Please resolve the conflicts.

**Comment by Sandesh1013** [comment]
@Jashpatel1 Resolved the conflicts

**Review by Jashpatel1 — CHANGES_REQUESTED** [review]
image

**Comment by Sandesh1013** [comment]
I have reverted the changes, code should compile now

**Review by Jashpatel1 — APPROVED** [review]

**Pull request merged**
